#pragma comment(lib,"ws2_32.lib")
#pragma once

#define PACKET_TOTAL				256
#define PACKET_SIZE					1
#define PACKET_INDEX				1
#define PACKET_STATE				1
#define PACKET_EXETYPE				1
#define PACKET_ROOMNUMBER			1
#define PACKET_NAME					20
#define PACKET_ORDER				1
#define PACKET_CHAT					80
#define PACKET_DEFINITION			1
#define PACKET_DATASIZE				1
#define PACKET_DATA		( PACKET_TOTAL      - PACKET_SIZE    - PACKET_INDEX - PACKET_STATE  \
	- PACKET_EXETYPE    - PACKET_ROOMNUMBER - PACKET_NAME  - PACKET_ORDER  \
	- PACKET_DEFINITION - PACKET_DATASIZE )

#define		PACKET_ROOM_DATAUPDATE		3
#define		PACKET_ROOM_CHAT			2

#define		THREAD_SUSPEND		0
#define		THREAD_RESUME		1
#define		THREAD_EXIT			2
#define		THREAD_WAIT_TIME	180		// 초

#define		BUFSIZE				1024
#define		PACKETREADY			0
#define		PACKETSEND			1
#define		PACKETRECV			1

#define		MAX_CONNECT			20
#define		MAX_ROOM_MEMBER		4
#define		MAX_ROOM			10


#define		CLIENT_DISCONNECT	0
#define		CLIENT_CONNECT		1
#define		CLIENT_LOBBY		2
#define		CLIENT_ROOM		3
#define		CLIENT_PLAY		4


enum eClientExe
{
	 CLIENT_CONNECT_NONE			
	,CLIENT_CONNECT_LOGIN		
	,CLIENT_CONNECT_MAKECHAR	
	,CLIENT_CONNECT_LOBBY	
	,CLIENT_CONNECT_ERROR	

};


#define		CLIENT_CONNECT_LOGIN_SHOW		1			// 로그인 화면으로 전환한다.
#define		CLIENT_CONNECT_MAKECHAR_SHOW	2
#define		CLIENT_CONNECT_LOBBY_SHOW		3
#define		CLIENT_CONNECT_ROOM_SHOW		4

enum eLobbyExe
{
	CLIENT_LOBBY_NONE
	,CLIENT_LOBBY_SHOW  
	,CLIENT_LOBBY_ROOM_LIST 
	,CLIENT_LOBBY_ROOM_INSERT
	,CLIENT_LOBBY_ROOM_DELETE
	,CLIENT_LOBBY_ROOM_JOIN 
	,CLIENT_LOBBY_CHAT  
	,CLIENT_LOBBY_ROOM_CREATE
	,CLIENT_LOBBY_ERROR
	,CLIENT_CONNECT_UPDATE
};


enum eLobbyError
{
	CREATE_ROOM_FAILE
};

enum eRoomExe
{
	CLIENT_ROOM_SHOW
	,CLIENT_ROOM_CREATE_UPDATE
	,CLIENT_ROOM_UPDATE
	,CLIENT_ROOM_USER_UPDATE
	,CLIENT_ROOM_USER_HOST_UPDATE
	,CLIENT_ROOM_USER_SCORE_UPDATE
	,CLIENT_ROOM_DELETE
	,CLIENT_ROOM_EXIT
	,CLIENT_ROOM_POSITION_RESET
	,CLIENT_ROOM_GAME_START
	,CLIENT_ROOM_PLAY
	,CLIENT_ROOM_RESET
	,CLIENT_ROOM_INIT
	,CLIENT_ROOM_CREATE_MODEL

};

 
#define  ROOM_NAME_SIZE		40   // 방이름 크기
#define  ROOM_PW_SIZE		10   // 패스워드 크기

#define		ROOM_NONE			-1
#define		ROOMINFO_NONE		0
#define		ROOMINFO_BEING		1
#define		SENDING_ALL			0
#define		SENDING_ROOM		1

#define		SERVER_STOP			0
#define		SERVER_WORKING		1

#define		MAX_PACKET			1024

enum eRoomState
{
	ROOM_STATE_EMPTY			 // 빈방
	,ROOM_STATE_READY			 // 시작전
	,ROOM_STATE_PLAY			 // 게임중

};

extern const char g_arrBehaviorName [][16];

const char g_arreDefinitionName [][16] =
{
	"DUMMY"
	,	"C_TRANSLATION"	
	,	"C_ROTATION"	
	,	"C_ANIMATION"		
	,	"C_MACRO"			
	,	"B_UPDATE"		
	,	"B_MACRO"		
};